[package]
name = "alloy-deadbeef"
version = "0.0.1"
edition = "2021"
authors = ["Pawel Urbanek <contact@pawelurbanek.com>"]
description = "0xdeadbeef"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pawurb/alloy-deadbeef"

[dependencies]
